ARG BUILD_IMAGE
FROM ${BUILD_IMAGE}

ARG GOLANGCI_VER
ENV PATH="/gopath/bin:${PATH}"

RUN curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GOPATH/bin ${GOLANGCI_VER}
RUN apt-get update && apt-get install -y libcap2-bin && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR "/go/src/github.com/gravitational/satellite/"
