// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agentpb/agent.proto

/*
Package agentpb is a generated protocol buffer package.

It is generated from these files:
	agentpb/agent.proto

It has these top-level messages:
	StatusRequest
	StatusResponse
	LocalStatusRequest
	LocalStatusResponse
	SystemStatus
	MemberStatus
	NodeStatus
	Probe
	Timestamp
*/
package agentpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SystemStatus_Type int32

const (
	SystemStatus_Unknown  SystemStatus_Type = 0
	SystemStatus_Running  SystemStatus_Type = 1
	SystemStatus_Degraded SystemStatus_Type = 2
)

var SystemStatus_Type_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Degraded",
}
var SystemStatus_Type_value = map[string]int32{
	"Unknown":  0,
	"Running":  1,
	"Degraded": 2,
}

func (x SystemStatus_Type) String() string {
	return proto.EnumName(SystemStatus_Type_name, int32(x))
}
func (SystemStatus_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type MemberStatus_Type int32

const (
	MemberStatus_None    MemberStatus_Type = 0
	MemberStatus_Alive   MemberStatus_Type = 1
	MemberStatus_Leaving MemberStatus_Type = 2
	MemberStatus_Left    MemberStatus_Type = 3
	MemberStatus_Failed  MemberStatus_Type = 4
)

var MemberStatus_Type_name = map[int32]string{
	0: "None",
	1: "Alive",
	2: "Leaving",
	3: "Left",
	4: "Failed",
}
var MemberStatus_Type_value = map[string]int32{
	"None":    0,
	"Alive":   1,
	"Leaving": 2,
	"Left":    3,
	"Failed":  4,
}

func (x MemberStatus_Type) String() string {
	return proto.EnumName(MemberStatus_Type_name, int32(x))
}
func (MemberStatus_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type NodeStatus_Type int32

const (
	NodeStatus_Unknown  NodeStatus_Type = 0
	NodeStatus_Running  NodeStatus_Type = 1
	NodeStatus_Degraded NodeStatus_Type = 2
)

var NodeStatus_Type_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Degraded",
}
var NodeStatus_Type_value = map[string]int32{
	"Unknown":  0,
	"Running":  1,
	"Degraded": 2,
}

func (x NodeStatus_Type) String() string {
	return proto.EnumName(NodeStatus_Type_name, int32(x))
}
func (NodeStatus_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type Probe_Type int32

const (
	Probe_Unknown    Probe_Type = 0
	Probe_Running    Probe_Type = 1
	Probe_Failed     Probe_Type = 2
	Probe_Terminated Probe_Type = 3
)

var Probe_Type_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Failed",
	3: "Terminated",
}
var Probe_Type_value = map[string]int32{
	"Unknown":    0,
	"Running":    1,
	"Failed":     2,
	"Terminated": 3,
}

func (x Probe_Type) String() string {
	return proto.EnumName(Probe_Type_name, int32(x))
}
func (Probe_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusResponse struct {
	Status *SystemStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StatusResponse) GetStatus() *SystemStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type LocalStatusRequest struct {
}

func (m *LocalStatusRequest) Reset()                    { *m = LocalStatusRequest{} }
func (m *LocalStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusRequest) ProtoMessage()               {}
func (*LocalStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LocalStatusResponse struct {
	Status *NodeStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *LocalStatusResponse) Reset()                    { *m = LocalStatusResponse{} }
func (m *LocalStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*LocalStatusResponse) ProtoMessage()               {}
func (*LocalStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LocalStatusResponse) GetStatus() *NodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// System describes the health status of the cluster.
type SystemStatus struct {
	Status SystemStatus_Type `protobuf:"varint,1,opt,name=status,enum=agentpb.SystemStatus_Type" json:"status,omitempty"`
	// Health status of individual nodes.
	Nodes     []*NodeStatus `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
	Timestamp *Timestamp    `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// Human-readable status summary.
	Summary string `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
}

func (m *SystemStatus) Reset()                    { *m = SystemStatus{} }
func (m *SystemStatus) String() string            { return proto.CompactTextString(m) }
func (*SystemStatus) ProtoMessage()               {}
func (*SystemStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SystemStatus) GetStatus() SystemStatus_Type {
	if m != nil {
		return m.Status
	}
	return SystemStatus_Unknown
}

func (m *SystemStatus) GetNodes() []*NodeStatus {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *SystemStatus) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *SystemStatus) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

// MembereStatus represents the status of a member of the serf cluster.
type MemberStatus struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Addr   string            `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	Status MemberStatus_Type `protobuf:"varint,3,opt,name=status,enum=agentpb.MemberStatus_Type" json:"status,omitempty"`
	Tags   map[string]string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MemberStatus) Reset()                    { *m = MemberStatus{} }
func (m *MemberStatus) String() string            { return proto.CompactTextString(m) }
func (*MemberStatus) ProtoMessage()               {}
func (*MemberStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MemberStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MemberStatus) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *MemberStatus) GetStatus() MemberStatus_Type {
	if m != nil {
		return m.Status
	}
	return MemberStatus_None
}

func (m *MemberStatus) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// NodeStatus represents a result of a health check for a single node.
type NodeStatus struct {
	Name         string          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	MemberStatus *MemberStatus   `protobuf:"bytes,2,opt,name=member_status,json=memberStatus" json:"member_status,omitempty"`
	Status       NodeStatus_Type `protobuf:"varint,3,opt,name=status,enum=agentpb.NodeStatus_Type" json:"status,omitempty"`
	// Probes lists all the health probes collected during the health check.
	Probes []*Probe `protobuf:"bytes,4,rep,name=probes" json:"probes,omitempty"`
}

func (m *NodeStatus) Reset()                    { *m = NodeStatus{} }
func (m *NodeStatus) String() string            { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()               {}
func (*NodeStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NodeStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeStatus) GetMemberStatus() *MemberStatus {
	if m != nil {
		return m.MemberStatus
	}
	return nil
}

func (m *NodeStatus) GetStatus() NodeStatus_Type {
	if m != nil {
		return m.Status
	}
	return NodeStatus_Unknown
}

func (m *NodeStatus) GetProbes() []*Probe {
	if m != nil {
		return m.Probes
	}
	return nil
}

type Probe struct {
	// Name of the checker that generated the probe.
	Checker string `protobuf:"bytes,1,opt,name=checker" json:"checker,omitempty"`
	// Optional detail specific to the checker
	Detail string `protobuf:"bytes,2,opt,name=detail" json:"detail,omitempty"`
	// Optional code specific to a checker (i.e. HTTP status code)
	Code   string     `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	Status Probe_Type `protobuf:"varint,4,opt,name=status,enum=agentpb.Probe_Type" json:"status,omitempty"`
	Error  string     `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (m *Probe) Reset()                    { *m = Probe{} }
func (m *Probe) String() string            { return proto.CompactTextString(m) }
func (*Probe) ProtoMessage()               {}
func (*Probe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Probe) GetChecker() string {
	if m != nil {
		return m.Checker
	}
	return ""
}

func (m *Probe) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Probe) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Probe) GetStatus() Probe_Type {
	if m != nil {
		return m.Status
	}
	return Probe_Unknown
}

func (m *Probe) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Timestamp struct {
	Seconds     int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	Nanoseconds int32 `protobuf:"varint,2,opt,name=nanoseconds" json:"nanoseconds,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanoseconds() int32 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "agentpb.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "agentpb.StatusResponse")
	proto.RegisterType((*LocalStatusRequest)(nil), "agentpb.LocalStatusRequest")
	proto.RegisterType((*LocalStatusResponse)(nil), "agentpb.LocalStatusResponse")
	proto.RegisterType((*SystemStatus)(nil), "agentpb.SystemStatus")
	proto.RegisterType((*MemberStatus)(nil), "agentpb.MemberStatus")
	proto.RegisterType((*NodeStatus)(nil), "agentpb.NodeStatus")
	proto.RegisterType((*Probe)(nil), "agentpb.Probe")
	proto.RegisterType((*Timestamp)(nil), "agentpb.Timestamp")
	proto.RegisterEnum("agentpb.SystemStatus_Type", SystemStatus_Type_name, SystemStatus_Type_value)
	proto.RegisterEnum("agentpb.MemberStatus_Type", MemberStatus_Type_name, MemberStatus_Type_value)
	proto.RegisterEnum("agentpb.NodeStatus_Type", NodeStatus_Type_name, NodeStatus_Type_value)
	proto.RegisterEnum("agentpb.Probe_Type", Probe_Type_name, Probe_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Agent service

type AgentClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	LocalStatus(ctx context.Context, in *LocalStatusRequest, opts ...grpc.CallOption) (*LocalStatusResponse, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/agentpb.Agent/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) LocalStatus(ctx context.Context, in *LocalStatusRequest, opts ...grpc.CallOption) (*LocalStatusResponse, error) {
	out := new(LocalStatusResponse)
	err := grpc.Invoke(ctx, "/agentpb.Agent/LocalStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Agent service

type AgentServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	LocalStatus(context.Context, *LocalStatusRequest) (*LocalStatusResponse, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agentpb.Agent/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_LocalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).LocalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agentpb.Agent/LocalStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).LocalStatus(ctx, req.(*LocalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agentpb.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Agent_Status_Handler,
		},
		{
			MethodName: "LocalStatus",
			Handler:    _Agent_LocalStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agentpb/agent.proto",
}

func init() { proto.RegisterFile("agentpb/agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0xff, 0xd2, 0x7a, 0x92, 0xe6, 0xb3, 0x36, 0xfd, 0x8a, 0x15, 0x90, 0x88, 0x7c, 0x81,
	0x8a, 0x10, 0xa1, 0x4a, 0x2f, 0x40, 0x05, 0x81, 0x8a, 0xf8, 0x91, 0x50, 0xa9, 0x90, 0x1b, 0xae,
	0xd1, 0x26, 0x1e, 0x42, 0xd4, 0x78, 0xd7, 0xac, 0x37, 0x41, 0x79, 0x0b, 0x2e, 0x79, 0x2a, 0x1e,
	0x03, 0x89, 0xb7, 0x40, 0xbb, 0x5e, 0x27, 0x76, 0x9a, 0x0a, 0x71, 0xe5, 0x9d, 0xb3, 0xb3, 0xc7,
	0x73, 0xce, 0xee, 0x0c, 0x74, 0xe8, 0x04, 0x99, 0xcc, 0x46, 0x8f, 0xf4, 0xb7, 0x9f, 0x09, 0x2e,
	0x39, 0xd9, 0x35, 0x60, 0xf4, 0x1f, 0xec, 0x5f, 0x4a, 0x2a, 0xe7, 0x79, 0x8c, 0x5f, 0xe7, 0x98,
	0xcb, 0xe8, 0x05, 0xb4, 0x4b, 0x20, 0xcf, 0x38, 0xcb, 0x91, 0x3c, 0x84, 0x46, 0xae, 0x91, 0xd0,
	0xea, 0x59, 0x47, 0xcd, 0xc1, 0xff, 0x7d, 0x73, 0xb8, 0x7f, 0xb9, 0xcc, 0x25, 0xa6, 0x26, 0xdd,
	0x24, 0x45, 0x07, 0x40, 0xce, 0xf9, 0x98, 0xce, 0xea, 0xb4, 0x2f, 0xa1, 0x53, 0x43, 0x0d, 0xf7,
	0x83, 0x0d, 0xee, 0xce, 0x8a, 0xfb, 0x82, 0x27, 0xb8, 0xc1, 0xfc, 0xdb, 0x82, 0x56, 0xf5, 0x97,
	0x64, 0x50, 0x3b, 0xdd, 0x1e, 0x74, 0xb7, 0x56, 0xd6, 0x1f, 0x2e, 0x33, 0x2c, 0x49, 0xc8, 0x7d,
	0xf0, 0x18, 0x4f, 0x30, 0x0f, 0xed, 0x9e, 0x73, 0xd3, 0x0f, 0x8b, 0x0c, 0x72, 0x0c, 0xbe, 0x9c,
	0xa6, 0x98, 0x4b, 0x9a, 0x66, 0xa1, 0xa3, 0xeb, 0x23, 0xab, 0xf4, 0x61, 0xb9, 0x13, 0xaf, 0x93,
	0x48, 0x08, 0xbb, 0xf9, 0x3c, 0x4d, 0xa9, 0x58, 0x86, 0x6e, 0xcf, 0x3a, 0xf2, 0xe3, 0x32, 0x8c,
	0xfa, 0xe0, 0xaa, 0x32, 0x48, 0x13, 0x76, 0x3f, 0xb2, 0x2b, 0xc6, 0xbf, 0xb1, 0x60, 0x47, 0x05,
	0xf1, 0x9c, 0xb1, 0x29, 0x9b, 0x04, 0x16, 0x69, 0xc1, 0xde, 0x2b, 0x9c, 0x08, 0x9a, 0x60, 0x12,
	0xd8, 0xd1, 0x0f, 0x1b, 0x5a, 0xef, 0x31, 0x1d, 0xa1, 0x30, 0x5a, 0x09, 0xb8, 0x8c, 0xa6, 0xa8,
	0x95, 0xfa, 0xb1, 0x5e, 0x2b, 0x8c, 0x26, 0x89, 0x08, 0xed, 0x02, 0x53, 0xeb, 0x8a, 0x27, 0xce,
	0x86, 0x27, 0x55, 0xba, 0xba, 0x27, 0x27, 0xe0, 0x4a, 0x3a, 0xc9, 0x43, 0x57, 0x5b, 0x72, 0xf7,
	0x86, 0x13, 0x74, 0x92, 0xbf, 0x66, 0x52, 0x2c, 0x63, 0x9d, 0xdc, 0x7d, 0x0c, 0xfe, 0x0a, 0x22,
	0x01, 0x38, 0x57, 0xb8, 0x34, 0xc5, 0xa9, 0x25, 0x39, 0x00, 0x6f, 0x41, 0x67, 0x73, 0x34, 0xc5,
	0x15, 0xc1, 0xa9, 0xfd, 0xc4, 0x8a, 0x9e, 0x1b, 0x2b, 0xf6, 0xc0, 0xbd, 0xe0, 0x0c, 0x83, 0x1d,
	0xe2, 0x83, 0x77, 0x36, 0x9b, 0x2e, 0x30, 0xb0, 0x94, 0x25, 0xe7, 0x48, 0x17, 0xca, 0x12, 0x5b,
	0x65, 0x9c, 0xe3, 0x67, 0x19, 0x38, 0x04, 0xa0, 0xf1, 0x86, 0x4e, 0x67, 0x98, 0x04, 0x6e, 0xf4,
	0xcb, 0x02, 0x58, 0x5f, 0xd6, 0x56, 0x63, 0x4e, 0x61, 0x3f, 0xd5, 0xb5, 0x7f, 0x32, 0x5e, 0xd8,
	0x1b, 0x2f, 0xb7, 0xaa, 0x2c, 0x6e, 0xa5, 0x55, 0xa3, 0x8f, 0x37, 0x0c, 0x0c, 0xb7, 0xbc, 0x90,
	0xba, 0x7d, 0xf7, 0xa0, 0x91, 0x09, 0x3e, 0xc2, 0xd2, 0xc0, 0xf6, 0xea, 0xc4, 0x07, 0x05, 0xc7,
	0x66, 0xf7, 0x9f, 0xdf, 0xc0, 0x4f, 0x0b, 0x3c, 0xcd, 0xa0, 0xde, 0xd5, 0xf8, 0x0b, 0x8e, 0xaf,
	0x50, 0x18, 0x99, 0x65, 0x48, 0x0e, 0xa1, 0x91, 0xa0, 0xa4, 0xd3, 0x99, 0xf1, 0xd9, 0x44, 0xca,
	0x95, 0x31, 0x4f, 0x50, 0x6b, 0xf0, 0x63, 0xbd, 0xae, 0x34, 0x9b, 0xab, 0x95, 0x75, 0xea, 0x75,
	0xd6, 0x45, 0x1d, 0x80, 0x87, 0x42, 0x70, 0x11, 0x7a, 0xc5, 0xfd, 0xe9, 0x20, 0x7a, 0xf6, 0x57,
	0x09, 0xeb, 0x9b, 0xb2, 0x49, 0x1b, 0x60, 0x88, 0x22, 0x9d, 0x32, 0x2a, 0x31, 0x09, 0x9c, 0xe8,
	0x2d, 0xf8, 0xc3, 0x5a, 0xaf, 0xe0, 0x98, 0xb3, 0xa4, 0xe8, 0x5e, 0x27, 0x2e, 0x43, 0xd2, 0x83,
	0x26, 0xa3, 0x8c, 0x97, 0xbb, 0x4a, 0x98, 0x17, 0x57, 0xa1, 0xc1, 0x77, 0x0b, 0xbc, 0x33, 0x55,
	0x3b, 0x79, 0x0a, 0x0d, 0x73, 0x6f, 0x87, 0xeb, 0xe6, 0xaf, 0x4e, 0x9e, 0xee, 0xad, 0x6b, 0x78,
	0x31, 0x7b, 0xa2, 0x1d, 0xf2, 0x0e, 0x9a, 0x95, 0xa1, 0x44, 0x6e, 0xaf, 0x32, 0xaf, 0x0f, 0xb0,
	0xee, 0x9d, 0xed, 0x9b, 0x25, 0xd7, 0xa8, 0xa1, 0x07, 0xeb, 0xc9, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x65, 0x57, 0x82, 0x99, 0x6f, 0x05, 0x00, 0x00,
}
