---

- hosts: nodes
  become: yes
  vars:
    root_dir: "{{playbook_dir}}/../.."
    creds_dir: "/var/lib/satellite/creds"
  tasks:

  - name: Ensure Satellite Directory Exists
    file:
      path: /var/lib/satellite
      state: directory
      mode: '755'

  - name: Ensure Credentials Directory Exists
    file:
      path: "{{creds_dir}}"
      state: directory
      mode: '755'

  - name: Upload CA certificate
    copy:
      dest: "{{creds_dir}}/ca.cert"
      content: |
        -----BEGIN CERTIFICATE-----
        MIIB8zCCAVWgAwIBAgIRAJV1RSNc5rvMx/+Y2Sls2l8wCgYIKoZIzj0EAwQwADAe
        Fw0xOTEwMjIyMDE5NTRaFw0yMDA0MTkyMDE5NTRaMAAwgZswEAYHKoZIzj0CAQYF
        K4EEACMDgYYABACGFuFJtaGW/8PsoAie8k3hPvIDuDLq0Zv2F8nBpGwy5+OgPEZf
        CTn80M/uei1fMM1v4lhIW60vobIVMDR19mYzkgG3I7mzCMe/9nds7Zqi5dObmJ28
        8v0TTymHX07ybeP0LOtqVsYaRD5vJM1V9hxMbg2lTyGZEwIGpS0uwTneQHq2EqNt
        MGswDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
        ATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdEQEB/wQfMB2CCWxvY2FsaG9zdIcEwKgy
        CocEwKgyC4cEwKgyDDAKBggqhkjOPQQDBAOBiwAwgYcCQWDodXaN6KXBXXSbMcfE
        Caa32n4FQpGawVFUdXAlfkuwZln6og3kF3rW/nZqMgXAyy5OWdRcgHfVRcKV2qKH
        MG4JAkIBFR9KhJpclw0Ggmt6r8RoC2Tm6NCoVO3qNZKvSYmP79MIIg2sGkZLqFll
        lwTm642wCaZoau8YfkaKk4SavUSSnik=
        -----END CERTIFICATE-----

  - name: Upload CA key
    copy:
      dest: "{{creds_dir}}/ca.key"
      content: |
        -----BEGIN EC PRIVATE KEY-----
        MIHcAgEBBEIBLVOewmcihM/Qgh5gc5hHp9Z/OUGOoOuOpT3WLfqGxA2+/MMP7YvN
        V+QAyRHAGJM4EOMM2MQajxOS/H5EXL1RvxKgBwYFK4EEACOhgYkDgYYABACGFuFJ
        taGW/8PsoAie8k3hPvIDuDLq0Zv2F8nBpGwy5+OgPEZfCTn80M/uei1fMM1v4lhI
        W60vobIVMDR19mYzkgG3I7mzCMe/9nds7Zqi5dObmJ288v0TTymHX07ybeP0LOtq
        VsYaRD5vJM1V9hxMbg2lTyGZEwIGpS0uwTneQHq2Eg==
        -----END EC PRIVATE KEY-----

  - name: Upload server certificate
    copy:
      dest: "{{creds_dir}}/server.cert"
      content: |
        -----BEGIN CERTIFICATE-----
        MIIB+jCCAVugAwIBAgIQINsz5OgowzGhJ74C61TynjAKBggqhkjOPQQDBDAAMB4X
        DTE5MTAyMjIwMTk1NFoXDTIwMDQxOTIwMTk1NFowADCBmzAQBgcqhkjOPQIBBgUr
        gQQAIwOBhgAEAL6VvpXwyw8lYbi7ZlVHEeGNjxR1L5bH+EqjOS7AnVeSUg+fuVTx
        3Xpmq9S9iln5aJUfa2QWi7J/8dpL5lU4sb+EABNRQp5iUU8GTNk4lJcRlWhGjjFr
        2bu9fSgllxm+7cRiJGZ9O9wTIBFMLD2y32RcQWYJwBpJGam9ugtQRyG516bFo3Qw
        cjAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMB
        MEEGA1UdEQEB/wQ3MDWCCWxvY2FsaG9zdIcEwKgyCocEwKgyC4cEwKgyDIcEfwAA
        AYcQAAAAAAAAAAAAAAAAAAAAATAKBggqhkjOPQQDBAOBjAAwgYgCQgH0HhVJri13
        rt3RqBH/3MMkDZJFfqKKs3l7u6u+bsFCD1AKiBRDQALO7dxzvAHcmWj4VQkPkb25
        XLJsO6NuKEJJ3AJCAZgfqiKJ23hXsAURr0OXh47v6LUNuDfnKGAsGlmJHUUi+9Bt
        orJb/oLHclk7YXKyUtZ98D/nGN/nTjv1IOWDhQae
        -----END CERTIFICATE-----

  - name: Upload server key
    copy:
      dest: "{{creds_dir}}/server.key"
      content: |
        -----BEGIN EC PRIVATE KEY-----
        MIHcAgEBBEIBXa2hGMGHzgHPxXBUI1jXbY7o7uMa7YQ/s0zyxfYjuSvAAXPc4WUP
        83BuNqeeZ6ZBYXSyK1WbBtXI0+QTfrHFQ0+gBwYFK4EEACOhgYkDgYYABAC+lb6V
        8MsPJWG4u2ZVRxHhjY8UdS+Wx/hKozkuwJ1XklIPn7lU8d16ZqvUvYpZ+WiVH2tk
        Fouyf/HaS+ZVOLG/hAATUUKeYlFPBkzZOJSXEZVoRo4xa9m7vX0oJZcZvu3EYiRm
        fTvcEyARTCw9st9kXEFmCcAaSRmpvboLUEchudemxQ==
        -----END EC PRIVATE KEY-----

  - name: Upload client certificate
    copy:
      dest: "{{creds_dir}}/client.cert"
      content: |
        -----BEGIN CERTIFICATE-----
        MIIB+jCCAVugAwIBAgIQTrkkSSdowIFqLZsHyGMg4DAKBggqhkjOPQQDBDAAMB4X
        DTE5MTAyMjIwMTk1NFoXDTIwMDQxOTIwMTk1NFowADCBmzAQBgcqhkjOPQIBBgUr
        gQQAIwOBhgAEAT1YA8sImGIxwIuttyG9RUgJFHUFKsVfrFXF8RSqYYe+vuQCe7DR
        ZO7MtRZp//37srLKj10gCg3eDBdRawR7cg4CAI6JlkO7wDK7JND0CKwd4hTIbQBQ
        Y9kQeEgOwgBrq1JepGW8v5Wfx6iEgHycQ+vqIcGmK6Gxver/j+ZOmC5gErmLo3Qw
        cjAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMB
        MEEGA1UdEQEB/wQ3MDWCCWxvY2FsaG9zdIcEwKgyCocEwKgyC4cEwKgyDIcEfwAA
        AYcQAAAAAAAAAAAAAAAAAAAAATAKBggqhkjOPQQDBAOBjAAwgYgCQgH8q7rZBbJy
        WeWIus+QURPKn9LF3WvfVBWzRoshDriBKj/K+YrdbAtY+FgTQnzRc0s6fJx4OMax
        3+Hcr0pc2+qtBQJCAIzx1SVwvpEmzh3Mwe5cBzSjaPhxEFrQVSTTVHcbIibfVKNn
        UUmIYXsHm8zrX4ZRCRUiTJJvlRY4U4wAofLBwnbj
        -----END CERTIFICATE-----

  - name: Upload client key
    copy:
      dest: "{{creds_dir}}/client.key"
      content: |
        -----BEGIN EC PRIVATE KEY-----
        MIHcAgEBBEIA8Vzy7wU6zvHnwcYwO0wBeIpeYshPNEql4COfvuCbcnEzkyd1gkan
        i8BHlp1LW+fdbAoseN2bjJa4gW7uJc01jZ2gBwYFK4EEACOhgYkDgYYABAE9WAPL
        CJhiMcCLrbchvUVICRR1BSrFX6xVxfEUqmGHvr7kAnuw0WTuzLUWaf/9+7Kyyo9d
        IAoN3gwXUWsEe3IOAgCOiZZDu8AyuyTQ9AisHeIUyG0AUGPZEHhIDsIAa6tSXqRl
        vL+Vn8eohIB8nEPr6iHBpiuhsb3q/4/mTpguYBK5iw==
        -----END EC PRIVATE KEY-----
