---

- hosts: nodes
  become: yes
  vars:
    root_dir: "{{playbook_dir}}/../.."
  tasks:

  - name: Register node IP
    shell: hostname -I | cut -d' ' -f2
    register: command_output
  - set_fact:
      node_ip: "{{command_output.stdout}}"

  # Install Serf
  - name: Install serf package
    apt:
      name: serf
      state: present
      update_cache: yes

  - name: Serf master config
    when: inventory_hostname in groups['first']
    copy:
      dest: /etc/serf/config.json
      content: |
        {
          "advertise": "{{node_ip}}",
          "tags": {
                  "role": "master"
          },
          "discover": "mycluster",
          "start_join": {{groups['nodes'] | to_json}},
        }

  - name: Serf node config
    when: inventory_hostname not in groups['first']
    copy:
      dest: /etc/serf/config.json
      content: |
        {
          "advertise": "{{node_ip}}",
          "tags": {
                  "role": "node"
          },
          "discover": "mycluster",
          "start_join": {{groups['nodes'] | to_json}},
        }

  - name: Restart serf
    service:
      name: serf
      daemon_reload: yes
      state: restarted

  - name: Join serf cluster
    when: inventory_hostname not in groups['first']
    command: serf join {{hostvars[groups['first'][0]]['node_ip']}}
